server:
  port: 8081


spring:
  application:
    name: consume-user #此实例（服务器）注册到eureka中的微服务名称

eureka:
  client:
    serviceUrl:
      #eureka服务端提供的注册地址（即eureka注册中心的地址） 参考服务端配置的这个路径
      defaultZone: http://eureka:3000/eureka,http://eureka:3001/eureka,http://eureka:3002/eureka
    register-with-eureka: true #当服务器启动时是否向eureka注册中心进行注册 默认是True

  instance:
    instance-id: user-1 #此实例（服务的一个实例，部署该服务的某台服务器）注册到eureka服务端的唯一的实例ID（用来区分服务的集群）
    prefer-ip-address: true #是否显示IP地址
    #eureka客户需要多长时间发送一次心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseRenewalIntervalInSeconds: 10
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为 90秒
    leaseExpirationDurationInSeconds: 30

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #超时时间
      circuitBreaker:
        requestVolumeThreshold: 5   #  10秒种访问5次某服务都失败的话, 会断开该服务,不会再调用该服务,直接进入fallback（降级方法）
        sleepWindowInMilliseconds: 30000   #默认是5秒 30秒后尝试再访问一次该服务的服务器(（试探性的先关闭熔断机制），如果这一次还是调用失败，则重新进行熔断
  threadpool:
    default:
      coreSize: 3 #hystrix给每个服务配置的线程池大小


feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能，让Feign支持hystrix

ribbon:
  ReadTimeout: 10000 #必须比hystrix配置的超时大否则，超时访问无效
  ConnectTimeout: 10000  #必须比hystrix配置的超时大否则，超时访问无效
